version: "3"

services:
  nginx-proxy:
    build: 
      context : ./bin/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx-proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx-proxy:/var/log/nginx
      - ./data/ssl/cert:/etc/ssl/cert
      - ./htdocs:/var/www
    networks:
      - backend
      - frontend
    restart: always
    depends_on: 
      - app1
      - app2  
  app1:
    build: 
      context: ./bin/php-73
    container_name: 'app-1'
    restart: 'always'
    ports:
      - "8080:8080"
    networks:
      - backend
    volumes: 
      - ./htdocs/app1:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/app1/vhosts:/etc/apache2/sites-enabled
      - ./config/app1/httpd/port.conf:/etc/apache2/ports.conf
      - ./logs/app1:/var/log/apache2
    depends_on: 
      - mysql
      - redis
  app2:
    build: 
      context: ./bin/php-72
    container_name: 'app-2'
    restart: 'always'
    ports:
      - "8080:8080"
    networks:
      - backend
    volumes: 
      - ./htdocs/app2:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/app2/vhosts:/etc/apache2/sites-enabled
      - ./config/app2/httpd/port.conf:/etc/apache2/ports.conf
      - ./logs/app2:/var/log/apache2
    depends_on: 
      - mysql
      - redis
  mysql:
    build:
      context: "./bin/mysql"
    container_name: '5.7.x-mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes: 
      - ./config/mysql:/etc/mysql/conf.d
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
  phpmyadmin:
    build:
      context: "./bin/pma"
    container_name: '5.0.2-phpmyadmin'
    networks:
      - backend
      - frontend
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      PMA_ABSOLUTE_URI: http://localhost:81
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '81:80'
    volumes: 
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    command: ${DISABLE_PMA}
    entrypoint: ${DISABLE_PMA}
    depends_on: 
      - mysql
  redis:
    container_name: '6.0.5-redis'
    command: redis-server --requirepass ${REDIS_PASS}
    build:
      context: "./bin/redis"
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - backend
networks:
  backend: 
    internal: true
    driver: bridge
  frontend:
    internal: false
    driver: bridge
